#@name get-prompts
GET http://localhost:3333/prompts

###

#@name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example2.mp3"
Content-Type: audio/mpeg

< ./example2.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
#@name create-transcription
POST http://localhost:3333/videos/1973402c-abf1-4d1b-b22e-c91e3231d408/transcription
Content-Type: application/json

{
    "prompt": "braço articulado, monitor, varias cores"
}


###
#@name gereration-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "1973402c-abf1-4d1b-b22e-c91e3231d408",
    "temperature": 0.5,
    "template": "Gere um resumo sucinto da trancrição do video informado a seguir: ''' {transcription}''' "
}
